build:

  environment:
    variables:
      ENV: 'ci'
      ACCEPTANCE_TESTS_PORT: 80
    mysql: false
    postgresql: false
    redis: false
    rabbitmq: false
    php:
      version: 7.1
      ini:
        'date.timezone': 'Europe/Amsterdam'
    docker:
      remote_engine: true
      cache:
        images:
          - 'php:7.1-alpine'
          - 'hgraca/explicit-architecture:app.sfn.base'

  tests:
    override:
      - command: export ACCEPTANCE_TESTS_HOST=$DOCKER_IP
      - command: make test-ci
        coverage:
          file: var/coverage.clover.xml
          format: php-clover
      - command: make test_cov-publish

  # Used for deployment.
  # Will only be executed if all tests succeeded.
  # If run in parallel, will be executed in the container where tests finish last.
  deployment:
    - branch: stg-*
      commands:
        - make deploy_stg-ci
    - branch: master
      commands:
        - make deploy_prd-ci

filter:
  paths:
    - "src/"
  dependency_paths:
    - "vendor/"

build_failure_conditions:
  - 'issues.new.exists'
  - 'project.metric_change("scrutinizer.test_coverage", < -0.05)'

checks:
  php:
    code_rating: true
    duplication: true
