apiVersion: v1
kind: Pod
metadata:
  name: blog-pod
spec:
  containers:
    - name: app
      image: hgraca/explicit-architecture:app.sfn.prd
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
      # defines the health checking
      livenessProbe:
        # an http probe
        httpGet:
          path: /
          port: 80
        # length of time to wait for a pod to initialize
        # after pod startup, before applying health checking
        initialDelaySeconds: 30
        timeoutSeconds: 1
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
  volumes:
    - name: secret-volume
      secret:
        secretName: blog-prod-env
